### ISSUE TITLE
bool File.rename(const char*) behaviour

### ISSUE THREAD

**Issue by yet-another-average-joe** [greiman/SdFat#157]
Hello,

I found a weird behaviour about File::rename()

This function fails if the source file is not open. Following the function calls, it calls FatFile::rename(). Reading the sources, it seems (to me...) that this function does not open the source file ("this") before copying.

Is this the expected behaviour ? The documentation does not explain that the file has to be kept open before copy. I mean : if the file is closed before renaming, the function fails. It's a bit counter intuitive : renaming an open file is not something we usually want to do...

Obviously, at file system level, SDFat::rename() does the job on a closed file ! It opens the file before calling FatFile::rename().

Maybe it could be worth mentioning this in the documentation : File::rename() needs the file to be open. (or I'm missing something !)

Context : a temp File, open FILE_WRITE, then closed, then renamed, reusing the File object = fail.

**Comment by greiman** [comment]
File:rename can't possible open a file.  In general it doesn't know which volume the file should be opened on.  Many users have multiple SD cards.

That's the purpose of 
`
bool FatFileSystem::rename (const char* oldPath, const char newPath)`

I do  not include the volume as part of path because that would require much additional code and memory and I only allow rename on a single volume, not rename that moves files between volumes.

My goal is to support  small boards like Uno with as many features as possible. and leave room for app code.

I will look at the documentation for the new version of [SdFat V2](https://github.com/greiman/SdFat-beta) now in beta.
