### ISSUE TITLE
DebugMacro output is hardcoded to Serial

### ISSUE THREAD

**Issue by cfeied** [greiman/SdFat#442]
It would be useful to allow DebugMacro output to be mapped to other serial ports.
I have submitted a trivial pull request for this.

**Comment by greiman** [comment]
I won't use this pull request since I only do bug fixes to the release version of SdFat.  Eventually this functionality will appear in [SdFat-beta](https://github.com/greiman/SdFat-beta).

I am working on a number new features, including really fast RP2040 SDIO based on PIO state machines, about 25 MB/sec read/write.

I have been modifying debug mode currently while I implement these features.
