### ISSUE TITLE
More details about the error occured

### ISSUE THREAD

**Issue by mvladic** [greiman/SdFat#86]
Library doesn't give any specificity about the error occurred. For example, when write fails I would like to know is it because disk is full. Do you think this is something that can be added to the library?

**Comment by greiman** [comment]
I am not adding features to SdFat.  I am only fixing bugs an any new development will be limited to[ SdFs](https://github.com/greiman/SdFs).

Checking for disk full is not very useful.  Your program will likely fail long before all space is used.  Generally it takes longer to find the last free clusters than to scan the FAT for the free cluster count.

The best plan is to call sd.freeClusterCount() just after sd.begin() and require substantial free space on the SD before running your program.

I may add error numbers to SdFs as an option, perhaps using [POSIX errno](http://pubs.opengroup.org/onlinepubs/009695399/functions/xsh_chap02_03.html) values.  The problem is the most common error will be:

> [EIO]
>     Input/output error. Some physical input or output error has occurred. This error may be reported on a subsequent operation on the same file descriptor. Any other error-causing operation on the same file descriptor may cause the [EIO] error indication to be lost.

The most common reason for writes to fail is a hardware error.  You can check for that by calling sd.cardErrorCode().  The 35-40 possible SD hardware error codes are listed in Sdinfo.h.

**Comment by mvladic** [comment]
Thanks!
